site_name: Design Documentation
site_description: Documentation for XR Design System
site_author: Souparna Roy
site_url: https://knorrsoupy.github.io/3DXR_Design-documentation/
site_language: en
site_keywords: XR, Design, System, 3DXR, Design System, XR Design System, XR Design System
repo_name: 3DXR_Design-docs
repo_url: https://github.com/knorrsoupy/3DXR_Design-documentation
theme:
  name: material
  font:
    text: Inter
    code: Red Hat Mono
  logo: ./assets/images/XR3D.svg # Path to the logo image
  favicon: ./assets/images/XR3D.svg # Path to the favicon image
  features:
     - navigation.path
     - navigation.instant
     - navigation.instant.prefetch
     - navigation.expand
     - navigation.footer
     - navigation.tracking
     - navigation.indexes
     - toc.integrate
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: teal

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: teal
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Concept Preview: core-concepts.md
  - Core Components:
      - Navigation : 
          - Navigation Types: navigation-patterns.md
          - Usecases : nav-usecases.md
      - HUD (Heads Up Display) : hud-ui-interfaces.md
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/squidfunk
copyright: Copyright © Souparna Roy